### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by River-Mochi**
- add hits badge.
- could not add downloads or other badges bc this repo has no release packages.

### CODE REVIEW

**Review by Ralim — CHANGES_REQUESTED** [review]
Can you change the Alt-Text from `Custom badge` to something more friendly to screen-readers?

**Comment by River-Mochi** [comment]
> u change the Alt-Text from `Custom badge`

do you mean the color right? change it from the  default black and grey?
the custom badge is named that bc I used the Shield.io to make it and it spits out the code. those colors for "hit" are default. I will change to brighter colors?

right now default looks like this
image
I will change it to blue or green or pink then.  there only 8 colors to pick from

**Comment by Ralim** [comment]
No i meant the text `Custom badge`.
Thats the alt-text for the image; so what is shown if the image cant be; or if your using a screen reader etc. So its best to try and make it understandable.

**Comment by River-Mochi** [comment]
since that was spit out by the Shields.io  program. I will probably not use shields.io 
and try the simpler  hit counter from https://hits.dwyl.com/

**Comment by River-Mochi** [comment]
`[HitCount](http://hits.dwyl.com/ralim/usb-pd)`

is the new code

**Comment by River-Mochi** [comment]
**Here are 4 choices given in  Shields.io.**  which of following is best for Screen readers?

**Markdown**
`Custom badge`

**reStructured text**
```
.. image:: https://img.shields.io/endpoint?url=https%3A%2F%2Fhits.dwyl.com%2Fralim%2Fusb-pd.json
   :alt: Custom badge
```
**AsciiDoc**
`image:https://img.shields.io/endpoint?url=https%3A%2F%2Fhits.dwyl.com%2Fralim%2Fusb-pd.json[Custom badge]`

**HTML**
`Custom badge`

**Comment by River-Mochi** [comment]
I think I got what you mean now,  you just want me to say  

`![HIT counter]` instead of  the default  '![Custom badge] '  word that they gave me in the Shields.io ?

Because we want to describe what the image is? 

that is simple.  now I know about screen readers, I had to look that up.

**Pull request closed without merging**
